### ISSUE TITLE
Name is too long

### ISSUE THREAD

**Issue by AvangionQ** [brainfubar/DeckSortMod#1]
Please shorten the name, remove the word Display ... hope you see this image, you'll see why immediately.

![image](https://user-images.githubusercontent.com/24449144/54371504-dddb2c80-464f-11e9-9abd-f0f2ec81acb2.png)

That's odd, the arrow I added isn't there ...

PS, this is an amazing mod ... thanks much for creating it.

**Comment by brainfubar** [comment]
You're right, that is kind of annoying. I've changed the name to "Deck Sort" and updated the workshop.
Deck Sort should be a more fitting name going forward: I've already updated the mod so the default order isn't strictly alphabetical anymore (it sorts by category before name,) and I'm considering adding a new mode that arranges the cards by energy cost, then name.
Thank you for your support!
